package com.atalayakilli.lol;

import android.util.Log;

import com.atalayakilli.lol.Models.Champions;

import java.util.ArrayList;
import java.util.List;

public class ChampionInformation {
    public static final List<Champions> fillChampions(){
        List<Champions> champions = new ArrayList<>();
        champions.add(new Champions(4,"Twisted Fate","TwistedFate"));
        champions.add(new Champions(202,"Jhin","Jhin"));
        champions.add(new Champions(67,"Vayne","Vayne"));
        champions.add(new Champions(64,"Lee Sin","LeeSin"));
        champions.add(new Champions(245,"Ekko","Ekko"));
        champions.add(new Champions(81,"Ezreal","Ezreal"));
        champions.add(new Champions(13,"Ryze","Ryze"));
        champions.add(new Champions(115,"Ziggs","Ziggs"));
        champions.add(new Champions(92,"Riven","Riven"));
        champions.add(new Champions(236,"Lucian","Lucian"));
        champions.add(new Champions(18,"Tristana","Tristana"));
        champions.add(new Champions(43,"Karma","Karma"));
        champions.add(new Champions(238,"Zed","Zed"));
        champions.add(new Champions(63,"Brand","Brand"));
        champions.add(new Champions(85,"Kennen","Kennen"));
        champions.add(new Champions(1,"Annie","Annie"));
        champions.add(new Champions(110,"Varus","Varus"));
        champions.add(new Champions(25,"Morgana","Morgana"));
        champions.add(new Champions(103,"Ahri","Ahri"));
        champions.add(new Champions(51,"Caitlyn","Caitlyn"));
        champions.add(new Champions(134,"Syndra","Syndra"));
        champions.add(new Champions(157,"Yasuo","Yasuo"));
        champions.add(new Champions(39,"Irelia","Irelia"));
        champions.add(new Champions(29,"Twitch","Twitch"));
        champions.add(new Champions(126,"Jayce","Jayce"));
        champions.add(new Champions(127,"Lissandra","Lissandra"));
        champions.add(new Champions(96,"Kog'Maw","KogMaw"));
        champions.add(new Champions(53,"Blitzcrank","Blitzcrank"));
        champions.add(new Champions(119,"Draven","Draven"));
        champions.add(new Champions(42,"Corki","Corki"));
        champions.add(new Champions(45,"Veigar","Veigar"));
        champions.add(new Champions(99,"Lux","Lux"));
        champions.add(new Champions(54,"Malphite","Malphite"));
        champions.add(new Champions(222,"Jinx","Jinx"));
        champions.add(new Champions(3,"Galio","Galio"));
        champions.add(new Champions(21,"Miss Fortune","MissFortune"));
        champions.add(new Champions(55,"Katarina","Katarina"));
        champions.add(new Champions(62,"Wukong","Wukong"));
        champions.add(new Champions(8,"Vladimir","Vladimir"));
        champions.add(new Champions(15,"Sivir","Sivir"));
        champions.add(new Champions(412,"Thresh","Thresh"));
        champions.add(new Champions(22,"Ashe","Ashe"));
        champions.add(new Champions(40,"Janna","Janna"));
        champions.add(new Champions(105,"Fizz","Fizz"));
        champions.add(new Champions(161,"Vel'Koz","Velkoz"));
        champions.add(new Champions(89,"Leona","Leona"));
        champions.add(new Champions(122,"Darius","Darius"));
        champions.add(new Champions(7,"Le Blanc","Leblanc"));
        champions.add(new Champions(91,"Talon","Talon"));
        champions.add(new Champions(76,"Nidalee","Nidalee"));
        champions.add(new Champions(104,"Graves","Graves"));
        champions.add(new Champions(59,"Jarvan IV","JarvanIV"));
        champions.add(new Champions(36,"Dr. Mundo","DrMundo"));
        champions.add(new Champions(121,"Kha'Zix","Khazix"));
        champions.add(new Champions(5,"Xin Zhao","XinZhao"));
        champions.add(new Champions(61,"Orianna","Orianna"));
        champions.add(new Champions(268,"Azir","Azir"));
        champions.add(new Champions(107,"Rengar","Rengar"));
        champions.add(new Champions(26,"Zilean","Zilean"));
        champions.add(new Champions(38,"Kassadin","Kassadin"));
        champions.add(new Champions(254,"Vi","Vi"));
        champions.add(new Champions(201,"Braum","Braum"));
        champions.add(new Champions(32,"Amumu","Amumu"));
        champions.add(new Champions(112,"Viktor","Viktor"));
        champions.add(new Champions(30,"Karthus","Karthus"));
        champions.add(new Champions(57,"Maokai","Maokai"));
        champions.add(new Champions(154,"Zac","Zac"));
        champions.add(new Champions(86,"Garen","Garen"));
        champions.add(new Champions(41,"Gangplank","Gangplank"));
        champions.add(new Champions(23,"Tryndamere","Tryndamere"));
        champions.add(new Champions(142,"Zoe","Zoe"));
        champions.add(new Champions(98,"Shen","Shen"));
        champions.add(new Champions(75,"Nasus","Nasus"));
        champions.add(new Champions(113,"Sejuani","Sejuani"));
        champions.add(new Champions(429,"Kalista","Kalista"));
        champions.add(new Champions(17,"Teemo","Teemo"));
        champions.add(new Champions(498,"Xayah","Xayah"));
        champions.add(new Champions(9,"Fiddlesticks","FiddleSticks"));
        champions.add(new Champions(58,"Renekton","Renekton"));
        champions.add(new Champions(101,"Xerath","Xerath"));
        champions.add(new Champions(131,"Diana","Diana"));
        champions.add(new Champions(24,"Jax","Jax"));
        champions.add(new Champions(82,"Mordekaiser","Mordekaiser"));
        champions.add(new Champions(111,"Nautilus","Nautilus"));
        champions.add(new Champions(421,"Rek'Sai","RekSai"));
        champions.add(new Champions(120,"Hecarim","Hecarim"));
        champions.add(new Champions(12,"Alistar","Alistar"));
        champions.add(new Champions(14,"Sion","Sion"));
        champions.add(new Champions(69,"Cassiopeia","Cassiopeia"));
        champions.add(new Champions(106,"Volibear","Volibear"));
        champions.add(new Champions(164,"Camille","Camille"));
        champions.add(new Champions(20,"Nunu and Willump","Nunu"));
        champions.add(new Champions(84,"Akali","Akali"));
        champions.add(new Champions(35,"Shaco","Shaco"));
        champions.add(new Champions(80,"Pantheon","Pantheon"));
        champions.add(new Champions(31,"Cho'Gath","Chogath"));
        champions.add(new Champions(44,"Taric","Taric"));
        champions.add(new Champions(56,"Nocturne","Nocturne"));
        champions.add(new Champions(11,"Master Yi","MasterYi"));
        champions.add(new Champions(266,"Aatrox","Aatrox"));
        champions.add(new Champions(10,"Kayle","Kayle"));
        champions.add(new Champions(555,"Pyke","Pyke"));
        champions.add(new Champions(267,"Nami","Nami"));
        champions.add(new Champions(90,"Malzahar","Malzahar"));
        champions.add(new Champions(2,"Olaf","Olaf"));
        champions.add(new Champions(37,"Sona","Sona"));
        champions.add(new Champions(223,"Tahm Kench","TahmKench"));
        champions.add(new Champions(117,"Lulu","Lulu"));
        champions.add(new Champions(79,"Gragas","Gragas"));
        champions.add(new Champions(143,"Zyra","Zyra"));
        champions.add(new Champions(48,"Trundle","Trundle"));
        champions.add(new Champions(74,"Heimerdinger","Heimerdinger"));
        champions.add(new Champions(102,"Shyvana","Shyvana"));
        champions.add(new Champions(133,"Quinn","Quinn"));
        champions.add(new Champions(33,"Rammus","Rammus"));
        champions.add(new Champions(136,"Aurelion Sol","AurelionSol"));
        champions.add(new Champions(163,"Taliyah","Taliyah"));
        champions.add(new Champions(34,"Anivia","Anivia"));
        champions.add(new Champions(16,"Soraka","Soraka"));
        champions.add(new Champions(83,"Yorick","Yorick"));
        champions.add(new Champions(114,"Fiora","Fiora"));
        champions.add(new Champions(68,"Rumble","Rumble"));
        champions.add(new Champions(60,"Elise","Elise"));
        champions.add(new Champions(420,"Illaoi","Illaoi"));
        champions.add(new Champions(203,"Kindred","Kindred"));
        champions.add(new Champions(432,"Bard","Bard"));
        champions.add(new Champions(19,"Warwick","Warwick"));
        champions.add(new Champions(28,"Evelyn","Evelyn"));
        champions.add(new Champions(150,"Gnar","Gnar"));
        champions.add(new Champions(427,"Ivern","Ivern"));
        champions.add(new Champions(240,"Kled","Kled"));
        champions.add(new Champions(78,"Poppy","Poppy"));
        champions.add(new Champions(27,"Singed","Singed"));
        champions.add(new Champions(72,"Skarner","Skarner"));
        champions.add(new Champions(50,"Swain","Swain"));
        champions.add(new Champions(77,"Udyr","Udyr"));
        champions.add(new Champions(6,"Urgot","Urgot"));
        champions.add(new Champions(145,"Kai'Sa","KaiSa"));
        champions.add(new Champions(141,"Kayn","Kayn"));
        champions.add(new Champions(497,"Rakan","Rakan"));
        return champions;
    }
}
